### ISSUE TITLE
pblk Initialization Failure

### ISSUE THREAD

**Issue by sooyun802** [Cosmos-OpenSSD/OCSSD-plus#2]
The host environment is Linux v4.18.

Attempts to create a pblk target with the following command fails.
```
sudo nvme lnvm create -d nvme0n1 -t pblk -n temp_tg -b 10 -e 11
```
This is the dmesg log.
```
[ 2011.064969] error:16384, ppa_status:0
[ 2011.066273] error:16384, ppa_status:0
[ 2011.067576] error:16384, ppa_status:0
[ 2011.068875] error:16384, ppa_status:0
[ 2011.070180] error:16384, ppa_status:0
[ 2011.071484] error:16384, ppa_status:0
[ 2011.072809] error:16384, ppa_status:0
[ 2011.074093] error:16384, ppa_status:0
[ 2011.075397] error:16384, ppa_status:0
[ 2011.076716] error:16384, ppa_status:0
[ 2011.078027] error:16384, ppa_status:0
[ 2011.079327] error:16384, ppa_status:0
[ 2011.080632] error:16384, ppa_status:0
[ 2011.081929] error:16384, ppa_status:0
[ 2011.083234] error:16384, ppa_status:0
[ 2011.084538] error:16384, ppa_status:0
[ 2011.085836] error:16384, ppa_status:0
[ 2011.087141] error:16384, ppa_status:0
[ 2011.088446] error:16384, ppa_status:0
[ 2011.089744] error:16384, ppa_status:0
[ 2011.091050] error:16384, ppa_status:0
[ 2011.092353] error:16384, ppa_status:0
[ 2011.093651] error:16384, ppa_status:0
[ 2011.094957] error:16384, ppa_status:0
[ 2011.096260] error:16384, ppa_status:0
[ 2011.097559] error:16384, ppa_status:0
[ 2011.098864] error:16384, ppa_status:0
[ 2011.098866] pblk: no free lines
[ 2011.099515] pblk: could not initialize maps
```
This command was tried several times with different combinations of `begin (-b)` and `end (-e)` values, but no combination seems to work.

We are currently using a single flash card with the Cosmos+ board, so we have adjusted the code to use only 4 channels. Other values that seem related to the number of channels were divided in half as well.

The following is the log acquired from the Cosmos+ board.
```
Write FAIL on             ch 01, lun 00, pl 1, bl 00700, pg 000, sec 0
Write FAIL on             ch 02, lun 01, pl 1, bl 01754, pg 000, sec 0
Write FAIL on             ch 02, lun 03, pl 0, bl 02532, pg 000, sec 0
Write FAIL on             ch 01, lun 01, pl 0, bl 03036, pg 000, sec 0
Write FAIL on             ch 01, lun 01, pl 0, bl 03136, pg 000, sec 0
Write FAIL on             ch 03, lun 06, pl 1, bl 03146, pg 000, sec 0
Write FAIL on             ch 03, lun 01, pl 0, bl 03170, pg 000, sec 0
Write FAIL on             ch 01, lun 03, pl 1, bl 03304, pg 000, sec 0
Write FAIL on             ch 03, lun 03, pl 0, bl 03398, pg 000, sec 0
Write FAIL on             ch 02, lun 03, pl 0, bl 03488, pg 000, sec 0
Write FAIL on             ch 00, lun 06, pl 0, bl 03804, pg 000, sec 0
Write FAIL on             ch 02, lun 03, pl 0, bl 03864, pg 000, sec 0
Write FAIL on             ch 01, lun 00, pl 1, bl 03972, pg 000, sec 0
Write FAIL on             ch 02, lun 04, pl 0, bl 04004, pg 000, sec 0
Write FAIL on             ch 01, lun 01, pl 0, bl 04010, pg 000, sec 0
Write FAIL on             ch 01, lun 01, pl 1, bl 04010, pg 000, sec 0
Write FAIL on             ch 01, lun 01, pl 1, bl 04026, pg 000, sec 0
Write FAIL on             ch 01, lun 00, pl 1, bl 04032, pg 000, sec 0
Write FAIL on             ch 00, lun 01, pl 1, bl 04070, pg 000, sec 0
Admin Command Done, OPC: 0xF2

Admin Command Done, OPC: 0xF2

Admin Command Done, OPC: 0xF2

Admin Command Done, OPC: 0xF2

Write FAIL on             ch 03, lun 06, pl 1, bl 00088, pg 000, sec 0
Write FAIL on             ch 03, lun 06, pl 1, bl 00184, pg 000, sec 0
Admin Command Done, OPC: 0xF2

Admin Command Done, OPC: 0xF2

Write FAIL on             ch 01, lun 07, pl 1, bl 00082, pg 000, sec 0
Admin Command Done, OPC: 0xF2

Admin Command Done, OPC: 0xF2
```

**Comment by Sangjin-Lee** [comment]
The DNR flag was set even if no IO error occurred. This may be the cause of the problem you are experiencing. Please try again with the latest firmware and let me know the progress.

**Comment by sooyun802** [comment]
With the latest firmware, I can now create a pblk target.

However, I can only make a target as big as about 36GB.

![image](https://user-images.githubusercontent.com/26572842/45349380-10966080-b5ec-11e8-9688-4a87858f39be.png)

When I try to set the end value bigger than 3, it still fails to create a target.
This is the dmesg log of the command: `sudo nvme lnvm create -d nvme0n1 -t pblk -n temp_tg -b 0 -e 7`
```
[  317.733818] pblk(temp_tg): luns:4, lines:4096, secs:10844160, buf entries:128
[  491.724162] pblk: flushing gc pipeline, 0 lines left
[  491.870138] pblk exit: L2P CRC: f1b6fa18
[  499.845909] nvme nvme0: bbt format mismatch
[  499.845922] pblk: could not initialize lines
```

**Comment by Sangjin-Lee** [comment]
Considering that you are using one NAND module, the problem seems to be caused by the firmware you've modified for one NAND module.
To change the firmware for two NAND modules to use only one NAND module, you need to make a number of changes.
I don't know how you modified the firmware so I can't give you the exact answer. However, I can tell you that OCSSD identify information or 'NAND or NAND controller' related parameters may be a problem.

**Comment by sooyun802** [comment]
I've just changed the number of channels to 4.
```
//#define USER_CHANNELS			NUMBER_OF_CHANNELS_ON_DEVICE
#define	USER_CHANNELS			(4)
```

**Comment by Sangjin-Lee** [comment]
Is [this line](https://github.com/Cosmos-OpenSSD/OCSSD-plus/blob/87a0466428363d230b543d849738e2394f30bd8d/OCSSD_DM_v1_0_17/nvme/nvme_identify.c#L240) you've modified?

**Comment by Sangjin-Lee** [comment]
Why do not you try changing the 'NUMBER_OF_CHANNELS_ON_DEVICE' of [the line](https://github.com/Cosmos-OpenSSD/OCSSD-plus/blob/87a0466428363d230b543d849738e2394f30bd8d/OCSSD_DM_v1_0_17/nvme/nvme_identify.c#L240) of your modified firmware to 'USER_CHANNELS' and try again?

**Comment by sooyun802** [comment]
I've changed the firmware as you've told me to do, but the same error occurs.
Are there any more lines I should modify?
